<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Lumo.Tools</RootNamespace>
    <AssemblyName>Lumo.Tools</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lumo.Engine\Lumo.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="2.88.9" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="2.88.9" />
  </ItemGroup>

</Project>
